workflows:
  android-workflow-debug:
    name: Android Workflow Debug
    max_build_duration: 60
    instance_type: mac_mini
    environment:      
      node: latest
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: release
          include: true
          source: true
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/local.properties"            
      - name: Install npm dependencies
        script: |
          yarn install
#          npm install --legacy-peer-deps
#          npm install --save-dev jetifier
#       - name: React Native Firebase
#         script: yarn add @react-native-firebase/app
#      - name: Install React Native Firebase
#        script: |
#          npm install --save @react-native-firebase/app
#      - name: Run Audit fix
#        script: |
#          npm audit fix
#      - name: Run npx jetify command
#        script: |
#          npx jetifier
      - name: Change mode for gradle permission
        working_directory: android
        script: |
          chmod +x gradlew
          ./gradlew --version
      - name: Build Gradle
        working_directory: android
        script: ./gradlew build
      - name: Build Android Debug APK
        working_directory: android
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/**/*.apk
    publishing:
      email:
        recipients:
          - balaji@pyramidions.co

  android-workflow-release:
    name: Android Workflow Release
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      node: latest
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: release
          include: true
          source: true
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/local.properties"
      - name: Install npm dependencies
        script: |
          yarn install
      - name: Change mode for gradle permission
        working_directory: android
        script: |
          chmod +x gradlew
          ./gradlew --version
      - name: Build Android Release APK
        working_directory: android
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/**/*.apk
    publishing:
      email:
        recipients:
          - balaji@pyramidions.co