require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
pod 'Firebase/Analytics'
pod 'Firebase/Auth'

#pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'
pod ‘RNFS’, :path => ‘../node_modules/react-native-fs’
pod 'react-native-document-picker', path: '../node_modules/react-native-document-picker'

platform :ios, '12.0'

target 'azzetta' do
  use_unimodules!
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  # permissions_path = '../node_modules/react-native-permissions/ios'
  # pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  # pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'Firebase/Messaging' 
  # pod 'Firebase/Core'
  # pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'
 
  # Uncomment to opt-in to using Flipper
  #
  # if !ENV['CI']
  #   use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
    # post_install do |installer|
    #   installer.pods_project.targets.each do |target|
    #     if target.name == "React-Core.common-AccessibilityResources" 
    #       target.remove_from_project 
    #     end
    #   end
    # end
  # end
  project 'azzetta.xcodepro'
  # pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

end
