export const config = {
	baseURL: 'http://13.126.78.148:3006/',
};
export const constants = {
	login: config.baseURL + 'app/appLogin',
	requestInvite: config.baseURL + 'app/requestInvite',
	requestInviteVerifyOtp: config.baseURL + 'app/requestInviteVerifyOtp',
	resendOtp: config.baseURL + 'app/resendOtp',
	checkInviteExist: config.baseURL + 'app/checkInviteExist',
	registerVerifyOtp: config.baseURL + 'app/registerVerifyOtp',
	listAllInvites: config.baseURL + 'app/listAllInvites',
	checkEmailNumberExist: config.baseURL + 'app/checkEmailNumberExist',
	postContacts: config.baseURL + 'app/postContacts',
	listContacts: config.baseURL + 'app/listContacts',
	syncContacts: config.baseURL + 'app/syncContacts',
	inviteContact: config.baseURL + 'app/inviteContact',
	checkMobileExist: config.baseURL + 'app/checkMobileExist',
	appMobileRegister: config.baseURL + 'app/appMobileRegister',
	appRegister: config.baseURL + 'app/appRegister',
	listDocumentType: config.baseURL + 'app/listDocumentType',
	listDocumentLocation: config.baseURL + 'app/listDocumentLocation',
	addDocument: config.baseURL + 'app/addDocument',
	listDocument: config.baseURL + 'app/listDocument',
	viewDocument: config.baseURL + 'app/viewDocument',
	applianceCategory: config.baseURL + 'app/listApplianceCategory',
	applianceType: config.baseURL + 'app/listApplianceType',
	applianceBrand: config.baseURL + 'app/listApplianceBrand',
	listApplianceModel: config.baseURL + 'app/listApplianceModel',
	addAppliance: config.baseURL + 'app/addAppliance',
	viewAppliance: config.baseURL + 'app/viewAppliance',
	listAppliance: config.baseURL + 'app/listAppliance',
	listApplianceCategory: config.baseURL + 'app/listApplianceCategory',
	updateDocumentExtra: config.baseURL + 'app/updateDocumentExtra',
	listDocumentReminder: config.baseURL + 'app/listDocumentReminder',
	updateApplianceExtra: config.baseURL + 'app/updateApplianceExtra',
	listApplianceReminder: config.baseURL + 'app/listApplianceReminder',
	updateDocumentReminder: config.baseURL + 'app/updateDocumentReminder',
	updateApplianceReminder: config.baseURL + 'app/updateApplianceReminder',
	listGeneralReminder: config.baseURL + 'app/listGeneralReminder',
	addUserReminder:config.baseURL + 'app/addUserReminder',
    addLocation: config.baseURL + 'app/addLocation',
	listAddLocation: config.baseURL + 'app/listAddLocation',
	ViewAddLocation: config.baseURL + 'app/ViewAddLocation',
	editLocation: config.baseURL + 'app/editLocation', 
	moveLocation: config.baseURL + 'app/moveLocation', 
	archiveLocation : config.baseURL + 'app/archiveLocation',
	editUserReminder: config.baseURL + 'app/editUserReminder',
	editAppliance: config.baseURL + 'app/editAppliance',
	listAssetLocation: config.baseURL + 'app/listAssetLocation',
	listApplianceShop: config.baseURL + 'app/listApplianceShop', 
};
