export const config = {
  baseURL: "http://188.166.228.50:3008/",
};
export const constants = {
  login: config.baseURL + "app/appLogin",
  requestInvite: config.baseURL + "app/requestInvite",
  requestInviteVerifyOtp: config.baseURL + "app/requestInviteVerifyOtp",
  resendOtp: config.baseURL + "app/resendOtp",
  checkInviteExist: config.baseURL + "app/checkInviteExist",
  registerVerifyOtp: config.baseURL + "app/registerVerifyOtp",
  listAllInvites: config.baseURL + "app/listAllInvites",
  checkEmailNumberExist: config.baseURL + "app/checkEmailNumberExist",
  postContacts: config.baseURL + "app/postContacts",
  listContacts: config.baseURL + "app/listContacts",
  inviteContact: config.baseURL + "app/inviteContact",
  checkMobileExist: config.baseURL + "app/checkMobileExist",
  appMobileRegister: config.baseURL + "app/appMobileRegister",
  appRegister: config.baseURL + "app/appRegister",
  listDocumentType: config.baseURL + "app/listDocumentType",
  listDocumentLocation: config.baseURL + "app/listDocumentLocation",
  addDocument: config.baseURL + "app/addDocument",
  listDocument: config.baseURL + "app/listDocument?page_no=1&page_limit=40",
  viewDocument: config.baseURL + "app/viewDocument",
  applianceCategory: config.baseURL + "app/listApplianceCategory",
  applianceType: config.baseURL + "app/listApplianceType",
  applianceBrand: config.baseURL + "app/listApplianceBrand",
  listApplianceModel: config.baseURL + "app/listApplianceModel",
  addAppliance: config.baseURL + "app/addAppliance",
  viewAppliance: config.baseURL + "app/viewAppliance",
  listAppliance: config.baseURL + "app/listAppliance",
};
